apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-lang-test
  replicas: 3
  template:
    metadata:
      labels:
        app: go-lang-test
    spec:
      containers:
        - name: go-lang-test
          image: >-
            registry.redhat.io/rhel8/go-toolset@sha256:2d56a94f1e83fe0e874f099dd8d03b876186985a7dbeea118e8c725b1b07b9f0
